"""empty message

Revision ID: 9796eaa0e02c
Revises: dd8f812d90f6
Create Date: 2024-05-10 11:36:33.899189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9796eaa0e02c'
down_revision: Union[str, None] = 'dd8f812d90f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answerCorrectness', 'reviewed_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answerCorrectness', 'reviewed_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
