"""empty message

Revision ID: a54a505d24b5
Revises: c44a0bbaf6f8
Create Date: 2024-05-10 17:36:46.422424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54a505d24b5'
down_revision: Union[str, None] = 'c44a0bbaf6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('role_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'sources', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'role_id')
    # ### end Alembic commands ###
