"""Drop todos table and add new tables

Revision ID: a97f97bf617c
Revises: 1d12fe2030e8
Create Date: 2024-05-10 11:15:25.199328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97f97bf617c'
down_revision: Union[str, None] = '1d12fe2030e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'updated_on')
    op.drop_column('questions', 'created_on')
    # ### end Alembic commands ###
