"""empty message

Revision ID: dd8f812d90f6
Revises: 63f930cd6bcf
Create Date: 2024-05-10 11:30:42.257374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8f812d90f6'
down_revision: Union[str, None] = '63f930cd6bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answerCorrectness', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('answerCorrectness', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'updated_on')
    op.drop_column('sources', 'created_on')
    op.drop_column('skills', 'updated_on')
    op.drop_column('skills', 'created_on')
    op.drop_column('answerCorrectness', 'updated_on')
    op.drop_column('answerCorrectness', 'created_on')
    # ### end Alembic commands ###
