"""empty message

Revision ID: dfca74174fcf
Revises: a91138f52115
Create Date: 2024-05-14 15:05:48.568977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfca74174fcf'
down_revision: Union[str, None] = 'a91138f52115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answerCorrectness_role_id_fkey', 'answerCorrectness', type_='foreignkey')
    op.drop_column('answerCorrectness', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answerCorrectness', sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('answerCorrectness_role_id_fkey', 'answerCorrectness', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
